### ISSUE TITLE
V 1.2.1.1 doesn't work with kodi 17.6

### ISSUE THREAD

**Issue by Goga777** [Nux007/Kodi-plugin.video.playlistLoader#2]
12:51:42.861 T:172977767664 DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.playlistLoader/?cache=0&iconimage&logos&mode=2&name=%5bnn%5d&url=http%3a%2f%2fiptv.denms.ru%2f%3frtnn%26goga777%26rikushok)
12:51:42.861 T:172977767664 DEBUG: ParentPath = [plugin://plugin.video.playlistLoader/]
12:51:42.873 T:173060089072 DEBUG: CAddonDatabase::SetLastUsed[plugin.video.playlistLoader] took 12 ms
12:51:42.874 T:173061125360 DEBUG: StartScript - calling plugin Playlist Loader('plugin://plugin.video.playlistLoader/','5','?cache=0&iconimage&logos&mode=2&name=%5bnn%5d&url=http%3a%2f%2fiptv.denms.ru%2f%3frtnn%26goga777%26rikushok')
12:51:42.874 T:173068477680 DEBUG: Thread LanguageInvoker start, auto delete: false
12:51:42.874 T:173068477680 INFO: initializing python engine.
12:51:42.874 T:173068477680 DEBUG: CPythonInvoker(9, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.playlistLoader/default.py): start processing
12:51:42.901 T:173068477680 DEBUG: -->Python Interpreter Initialized<--
12:51:42.901 T:173068477680 DEBUG: CPythonInvoker(9, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.playlistLoader/default.py): the source file to load is "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.playlistLoader/default.py"
12:51:42.902 T:173068477680 DEBUG: CPythonInvoker(9, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.playlistLoader/default.py): setting the Python path to /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.playlistLoader:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.certifi/lib:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.chardet/lib:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.idna/lib:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib:/:/data/app/org.xbmc.kodi-Z74sE-ioEvEHz6w7Rx77Ew==/base.apk/assets/python2.7/lib/python27.zip:/data/app/org.xbmc.kodi-Z74sE-ioEvEHz6w7Rx77Ew==/base.apk/assets/python2.7/lib/python2.7:/data/app/org.xbmc.kodi-Z74sE-ioEvEHz6w7Rx77Ew==/base.apk/assets/python2.7/lib/python2.7/plat-linux2:/data/app/org.xbmc.kodi-Z74sE-ioEvEHz6w7Rx77Ew==/base.apk/assets/python2.7/lib/python2.7/lib-tk:/data/app/org.xbmc.kodi-Z74sE-ioEvEHz6w7Rx77Ew==/base.apk/assets/python2.7/lib/python2.7/lib-old:/data/app/org.xbmc.kodi-Z74sE-ioEvEHz6w7Rx77Ew==/base.apk/assets/python2.7/lib/python2.7/lib-dynload
12:51:42.902 T:173068477680 DEBUG: CPythonInvoker(9, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.playlistLoader/default.py): entering source directory /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.playlistLoader
12:51:42.903 T:173068477680 DEBUG: CPythonInvoker(9, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.playlistLoader/default.py): instantiating addon using automatically obtained id of "plugin.video.playlistLoader" dependent on version 2.1.0 of the xbmc.python api
12:51:43.363 T:172977767664 DEBUG: ------ Window Init (DialogBusy.xml) ------
12:51:43.741 T:173068477680 ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.playlistLoader/default.py:147: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
matches = [groupChannels.index(x) for x in groupChannels if len(x) > 0 and x[0].get("group_title", x[0]["display_name"]) == channel.get("group_title", channel["display_name"])]
12:51:44.512 T:173068477680 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.KeyError'>
Error Contents: ('tvg_logo',)
Traceback (most recent call last):
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.playlistLoader/default.py", line 394, in 
m3uCategory(url, logos, cache, index)
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.playlistLoader/default.py", line 170, in m3uCategory
image = channel['tvg_logo'] if meta is None else meta[channel["group_title"]]["poster"] if channel["group_title"] in meta else channel['tvg_logo']
KeyError: ('tvg_logo',)
-->End of Python script error report<--
12:51:44.529 T:172977767664 DEBUG: ------ Window Init (DialogNotification.xml) ------
12:51:44.560 T:173068477680 INFO: Python script stopped
12:51:44.560 T:173068477680 DEBUG: Thread LanguageInvoker 173068477680 terminating
12:51:44.566 T:172977767664 ERROR: GetDirectory - Error getting plugin://plugin.video.playlistLoader/?cache=0&iconimage&logos&mode=2&name=%5bnn%5d&url=http%3a%2f%2fiptv.denms.ru%2f%3frtnn%26goga777%26rikushok
12:51:44.568 T:172977767664 ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.playlistLoader/?cache=0&iconimage&logos&mode=2&name=%5bnn%5d&url=http%3a%2f%2fiptv.denms.ru%2f%3frtnn%26goga777%26rikushok) failed
12:51:44.568 T:172977767664 DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.playlistLoader/)
12:51:44.568 T:172977767664 DEBUG: ParentPath = [addons://sources/video]
12:51:44.577 T:173060089072 DEBUG: CAddonDatabase::SetLastUsed[plugin.video.playlistLoader] took 9 ms
12:51:44.578 T:173061125360 DEBUG: StartScript - calling plugin Playlist Loader('plugin://plugin.video.playlistLoader/','6','')
12:51:44.578 T:173068477680 DEBUG: Thread LanguageInvoker start, auto delete: false
12:51:44.578 T:173068477680 INFO: initializing python engine.
12:51:44.578 T:173068477680 DEBUG: CPythonInvoker(10, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.playlistLoader/default.py): start processing
12:51:44.597 T:173068477680 DEBUG: -->Python Interpreter Initialized<--
12:51:44.597 T:173068477680 DEBUG: CPythonInvoker(10, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.playlistLoader/default.py): the source file to load is "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.playlistLoader/default.py"
12:51:44.598 T:173068477680 DEBUG: CPythonInvoker(10, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.playlistLoader/default.py): setting the Python path to /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.playlistLoader:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.certifi/lib:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.chardet/lib:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.idna/lib:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib:/:/data/app/org.xbmc.kodi-Z74sE-ioEvEHz6w7Rx77Ew==/base.apk/assets/python2.7/lib/python27.zip:/data/app/org.xbmc.kodi-Z74sE-ioEvEHz6w7Rx77Ew==/base.apk/assets/python2.7/lib/python2.7:/data/app/org.xbmc.kodi-Z74sE-ioEvEHz6w7Rx77Ew==/base.apk/assets/python2.7/lib/python2.7/plat-linux2:/data/app/org.xbmc.kodi-Z74sE-ioEvEHz6w7Rx77Ew==/base.apk/assets/python2.7/lib/python2.7/lib-tk:/data/app/org.xbmc.kodi-Z74sE-ioEvEHz6w7Rx77Ew==/base.apk/assets/python2.7/lib/python2.7/lib-old:/data/app/org.xbmc.kodi-Z74sE-ioEvEHz6w7Rx77Ew==/base.apk/assets/python2.7/lib/python2.7/lib-dynload
12:51:44.598 T:173068477680 DEBUG: CPythonInvoker(10, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.playlistLoader/default.py): entering source directory /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.playlistLoader
12:51:44.598 T:173068477680 DEBUG: CPythonInvoker(10, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.playlistLoader/default.py): instantiating addon using automatically obtained id of "plugin.video.playlistLoader" dependent on version 2.1.0 of the xbmc.python api
12:51:45.069 T:172977767664 DEBUG: ------ Window Init (DialogBusy.xml) ------
12:51:45.339 T:173068477680 INFO: CPythonInvoker(10, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.playlistLoader/default.py): script successfully run
12:51:45.372 T:172977767664 DEBUG: RunQuery took 0 ms for 77 items query: SELECT files.strFilename, files.playCount, bookmark.timeInSeconds, bookmark.totalTimeInSeconds FROM files LEFT JOIN bookmark ON files.idFile = bookmark.idFile AND bookmark.type = 1 WHERE files.idPath=27
12:51:45.382 T:173127173360 DEBUG: Thread BackgroundLoader start, auto delete: false
12:51:45.391 T:173068477680 INFO: Python script stopped
12:51:45.391 T:173068477680 DEBUG: Thread LanguageInvoker 173068477680 terminating
12:51:45.391 T:172977767664 DEBUG: Keyboard: scancode: 0x17, sym: 0x000d, unicode: 0x0000, modifier: 0x0
12:51:45.392 T:172977767664 DEBUG: [Warning] CGUITextureManager::GetTexturePath: could not find texture 'OverlayUnwatched.png'
12:51:45.401 T:173127173360 DEBUG: Previous line repeats 13 times.
12:51:45.401 T:173127173360 DEBUG: Thread BackgroundLoader 173127173360 terminating
12:51:45.547 T:172977767664 DEBUG: ------ Window Deinit (DialogBusy.xml) ------
12:51:49.809 T:172977767664 DEBUG: ------ Window Deinit (DialogNotification.xml) ------
goga@debian:~/kodi/log$

**Comment by Nux007** [comment]
Hi @Goga777 thank's for the report. Please, use a pastebin like service to provide your logs in the future so it will be more readable ;-)

**Comment by Nux007** [comment]
Please, download the zip file from the **dev branch** and tell me if it fix your problem.
Thank's

**Comment by Goga777** [comment]
yes, dev branch is working well

sorry for the paste, yes i will use pastebinit in the futiure.
