### ISSUE TITLE
what is your nearest plans for the addon?

### ISSUE THREAD

**Issue by Goga777** [Nux007/Kodi-plugin.video.playlistLoader#3]
i think you have some plan to improve the addon. If yes, would you like pls share your plans.
merci

**Comment by Nux007** [comment]
I plan to nearly finish thetvdb and theoviedb full integration that a started some times ago ... Also maybe metalliQ player and other things to match users needs :-)

**Comment by Goga777** [comment]
can you check and to add if need the support for those tags in m3u file

#EXTINF tvg-logo
#EXTINF group-title
#EXTGRP
#EXTINF catchup-source
#EXTINF tvg-id
#EXTINF tvg-name
