### ISSUE TITLE
Where does this app store the playlist file?

### ISSUE THREAD

**Issue by leopheard** [Nux007/Kodi-plugin.video.playlistLoader#9]
Where does this app store the playlist file please?

**Comment by Nux007** [comment]
`addon_data_dir = xbmc.translatePath(Addon.getAddonInfo("profile")).decode("utf-8")`
`playlistsFile = os.path.join(addon_data_dir, "playLists.txt")`
`vDirectoriesFile = os.path.join(addon_data_dir, "virtual_directoriesLists.txt")`
`tmpListFile = os.path.join(addon_data_dir, 'tempList.txt')`
`favoritesFile = os.path.join(addon_data_dir, 'favorites.txt')`

**Comment by Nux007** [comment]
No interactions
